from sqlalchemy import orm
from current_affairs.database import CurrentAffair, Highlight, Image, Keyword


INVALID_TITLE_PATTERNS = [
    "403 forbidden",
    "http 403",
    "404 not found",
    "url not found",
    "url not",
    "access denied",
    "page not found",
    "blocked by",
    "untitled topic",
    "current_affairs_topic",
    "dummy",
    "test topic",
    "lorem ipsum",
]

DUMMY_CONTENT_INDICATORS = [
    "lorem ipsum",
    "sample description",
    "test content",
    "dummy text",
    "placeholder",
    "add description here",
]


def is_error_page_title(title: str) -> bool:
    """Return True if the title indicates an HTTP error or blocked page."""
    check = (title or "").lower().strip()
    return any(p in check for p in INVALID_TITLE_PATTERNS)


def is_dummy_content(text: str) -> bool:
    """Return True if the content contains known placeholder or dummy phrases."""
    check = (text or "").lower().strip()
    return any(d in check for d in DUMMY_CONTENT_INDICATORS)


def classify_failure_reason(exc: Exception, url: str) -> tuple[str, str]:
    """
    Classify failures into human-readable reasons and technical categories.
    Returns (category, reason).
    """
    msg = str(exc)
    msg_lower = msg.lower()

    if not url or not str(url).strip().startswith("http"):
        return "INVALID_LINK", "Link incorrect: Missing or invalid URL format"

    if any(k in msg_lower for k in ["403", "waf", "blocked", "captcha", "cloudflare", "access denied", "forbidden"]):
        return "SCRAPING_BLOCKED", "Scraping not possible: Site blocked access (HTTP 403 / Cloudflare / WAF protection)"

    if "insufficient article content" in msg_lower or "content retrieved" in msg_lower:
        return "CONTENT_INSUFFICIENT", "Scraping not possible: Page body content was empty or insufficient (< 50 chars)"

    if "perplexity api failed" in msg_lower or "no content generated by perplexity" in msg_lower:
        return "LLM_SYNTHESIS_FAILED", f"Content generation error: LLM failed to produce UPSC notes ({msg[:100]})"

    if "error page" in msg_lower:
        return "SCRAPING_BLOCKED", f"Scraping not possible: Extracted page was an error message ({msg[:100]})"

    if "could not parse date" in msg_lower or "missing date" in msg_lower:
        return "MISSING_DATE", f"Date format error: {msg}"

    return "PROCESSING_ERROR", f"Processing error: {msg[:150]}"


def validate_article_for_db(article_id: int, db: orm.Session) -> tuple[bool, list[str]]:
    """
    Perform rigorous DB validation to ensure an article is 100% complete and contains no dummy content.
    Returns (is_valid, list_of_issues).
    Used prior to promoting articles from Dev -> Test -> Prod.
    """
    issues = []

    ca = db.query(CurrentAffair).filter(CurrentAffair.id == article_id).first()
    if not ca:
        return False, [f"Article ID {article_id} does not exist in mtr_current_affairs_edk"]

    # 1. Topic validation
    if not ca.topic or len(ca.topic.strip()) < 10:
        issues.append(f"Topic is too short or missing: '{ca.topic}'")
    elif is_error_page_title(ca.topic):
        issues.append(f"Topic contains error or dummy marker: '{ca.topic}'")
    elif is_dummy_content(ca.topic):
        issues.append(f"Topic contains dummy content: '{ca.topic}'")

    # 2. Content (subtitle) validation
    if not ca.content or len(ca.content.strip()) < 20:
        issues.append("Content (subtitle) is missing or less than 20 characters")
    elif is_dummy_content(ca.content):
        issues.append("Content contains dummy placeholder text")

    # 3. Taxonomy validation
    if not ca.theme or not ca.theme_topic or not ca.theme_subtopic:
        issues.append(f"Taxonomy incomplete: theme='{ca.theme}', topic='{ca.theme_topic}', subtopic='{ca.theme_subtopic}'")

    # 4. Highlight validation
    hl = db.query(Highlight).filter(Highlight.id == article_id).first()
    if not hl or not hl.highlight_text:
        issues.append(f"Missing highlight record in mtr_ca_highlights_edk for article {article_id}")
    else:
        hl_text = hl.highlight_text
        if len(hl_text.strip()) < 400:
            issues.append(f"Highlight content is too short ({len(hl_text)} chars, expected > 400)")
        if "#####" not in hl_text:
            issues.append("Highlight is missing standard UPSC level-5 markdown headers")
        if is_dummy_content(hl_text):
            issues.append("Highlight contains dummy content")

    # 5. Image record & Blob URL validation
    img = db.query(Image).filter(Image.id == article_id).first()
    if not img or not img.image_url:
        issues.append(f"Missing image record in mtr_ca_images_edk for article {article_id}")
    else:
        expected_suffix = f"/{article_id}.jpg"
        if not img.image_url.endswith(expected_suffix):
            issues.append(f"Image URL '{img.image_url}' does not end with expected '{expected_suffix}'")

    # 6. Keyword validation
    kw = db.query(Keyword).filter(Keyword.id == article_id).first()
    if not kw or not kw.kword:
        issues.append(f"Missing keywords record in mtr_ca_kword_edk for article {article_id}")
    elif len(kw.kword.split(",")) < 2:
        issues.append(f"Insufficient keywords count (got: '{kw.kword}')")

    is_valid = len(issues) == 0
    return is_valid, issues
